/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.KontakController; 
import java.awt.Color;
import java.io.*; 
import model.Kontak; 
import javax.swing.*; 
import javax.swing.table.DefaultTableModel; 
import java.sql.SQLException; 
import java.util.List; 
import java.util.logging.Level; 
import java.util.logging.Logger; 
import java.util.ArrayList; 

/**
 *
 * @author Dimas
 */
public class PengelolaanKontakFrame extends javax.swing.JFrame {
    
    private DefaultTableModel model; 
    private KontakController controller;
    
    private DefaultListModel<String> listModel = new DefaultListModel<>();
    
    private boolean isFiltering = false;
    
    private List<Kontak> currentContacts = new ArrayList<>();
    /**
     * Creates new form PengelolaanKontakFrame
     */
    // Constructor untuk inisialisasi komponen GUI dan setup awal
    public PengelolaanKontakFrame() {
        initComponents();
        
        setPlaceholder(txtNama, "Masukkan nama");
        setPlaceholder(txtNomorTelepon, "Masukkan nomor");
        setPlaceholder(txtPencarian, "Cari kontak");

        jPanel1.requestFocusInWindow();
        controller = new KontakController(); 
        
        model = new DefaultTableModel(new String[]{"No", "Nama", "Nomor Telepon", "Kategori"}, 0); 
        tblKontak.setModel(model); 
        
        listkontak.setModel(listModel);
        
        loadContacts();
        
        listkontak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int index = listkontak.getSelectedIndex();
                if (index != -1 && index < currentContacts.size()) {
                    Kontak selectedContact = currentContacts.get(index);

                    txtNama.setText(selectedContact.getNama());
                    txtNama.setForeground(Color.BLACK);

                    txtNomorTelepon.setText(selectedContact.getNomorTelepon());
                    txtNomorTelepon.setForeground(Color.BLACK);

                    cmbKategori.setSelectedItem(selectedContact.getKategori());
                }
            }
        });
    }
    
    // Method untuk mengatur placeholder text pada JTextField
    private void setPlaceholder(JTextField field, String placeholderText) {
        field.setForeground(Color.GRAY);
        field.setText(placeholderText);
        field.putClientProperty("placeholder", placeholderText);

        field.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                String currentPlaceholder = (String) field.getClientProperty("placeholder");
                if(field.getText().equals(currentPlaceholder) && 
                   field.getForeground().equals(Color.GRAY)) {
                    field.setText("");
                    field.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if(field.getText().trim().isEmpty()) {
                    String currentPlaceholder = (String) field.getClientProperty("placeholder");
                    field.setText(currentPlaceholder);
                    field.setForeground(Color.GRAY);
                }
            }
        });
    }
    
    // Method untuk mereset field input ke kondisi placeholder
    private void resetField(JTextField field) {
        String placeholder = (String) field.getClientProperty("placeholder");
        if (placeholder != null) {
            field.setText(placeholder);
            field.setForeground(Color.GRAY);
        } else {
            field.setText("");
            field.setForeground(Color.BLACK);
        }
    }
    
    // Method untuk mendapatkan text sebenarnya (bukan placeholder)
    private String getActualText(JTextField field) {
        String text = field.getText().trim();
        String placeholder = (String) field.getClientProperty("placeholder");
        
        if (placeholder != null && text.equals(placeholder) && 
            field.getForeground().equals(Color.GRAY)) {
            return "";
        }
        return text;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblKontak = new javax.swing.JLabel();
        lblTelepon = new javax.swing.JLabel();
        lblKategori = new javax.swing.JLabel();
        lblPencarian = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNomorTelepon = new javax.swing.JTextField();
        txtPencarian = new javax.swing.JTextField();
        cmbKategori = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKontak = new javax.swing.JTable();
        btnExport = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listkontak = new javax.swing.JList<>();
        btnCariKntk = new javax.swing.JButton();
        lblDaftarKntk = new javax.swing.JLabel();
        lblFilter = new javax.swing.JLabel();
        cmbFilterKategori = new javax.swing.JComboBox<>();
        btnTampilkanSemua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Pengelolaan Kontak ");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(255, 255, 255));
        lblJudul.setText("APLIKASI PENGELOLAAN  KONTAK ");
        jPanel1.add(lblJudul);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblKontak.setText("Nama Kontak :");

        lblTelepon.setText("Nomor Telepon :");

        lblKategori.setText("Kategori :");

        lblPencarian.setText("Pencarian :");

        txtPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPencarianKeyTyped(evt);
            }
        });

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Keluarga", "Teman", "Kantor" }));

        btnTambah.setBackground(new java.awt.Color(40, 167, 69));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/add.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 123, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(220, 53, 69));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/delete.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tblKontak.setBackground(new java.awt.Color(204, 204, 204));
        tblKontak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Nomor Telepon", "Kategori"
            }
        ));
        tblKontak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKontakMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKontak);

        btnExport.setBackground(new java.awt.Color(204, 204, 204));
        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/export.png"))); // NOI18N
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnImport.setBackground(new java.awt.Color(204, 204, 204));
        btnImport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/download.png"))); // NOI18N
        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(204, 204, 204));
        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logout.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        jScrollPane2.setPreferredSize(new java.awt.Dimension(120, 90));

        jScrollPane2.setViewportView(listkontak);

        btnCariKntk.setBackground(new java.awt.Color(23, 162, 184));
        btnCariKntk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/search.png"))); // NOI18N
        btnCariKntk.setText("Cari Kontak");
        btnCariKntk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariKntkActionPerformed(evt);
            }
        });

        lblDaftarKntk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDaftarKntk.setText("Daftar Kontak :");

        lblFilter.setText("Filter Kategori :");

        cmbFilterKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Keluarga", "Teman", "Kantor" }));
        cmbFilterKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFilterKategoriActionPerformed(evt);
            }
        });

        btnTampilkanSemua.setBackground(new java.awt.Color(108, 117, 125));
        btnTampilkanSemua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/file.png"))); // NOI18N
        btnTampilkanSemua.setText("Tampilkan Semua");
        btnTampilkanSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanSemuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDaftarKntk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPencarian)
                            .addComponent(lblKategori)
                            .addComponent(lblTelepon)
                            .addComponent(lblKontak)
                            .addComponent(lblFilter))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPencarian)
                            .addComponent(cmbKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNomorTelepon)
                            .addComponent(txtNama)
                            .addComponent(cmbFilterKategori, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnExport)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnImport)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnKeluar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnCariKntk, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTampilkanSemua)
                                .addGap(29, 29, 29)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKontak))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelepon)
                    .addComponent(txtNomorTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKategori))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapus)
                            .addComponent(btnEdit)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnTambah)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPencarian))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilter)
                    .addComponent(cmbFilterKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCariKntk)
                    .addComponent(btnTampilkanSemua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDaftarKntk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKeluar)
                    .addComponent(btnImport)
                    .addComponent(btnExport))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Event handler untuk tombol Tambah
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        addContact();
    }//GEN-LAST:event_btnTambahActionPerformed
    
    // Event handler untuk tombol Edit
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        editContact();
    }//GEN-LAST:event_btnEditActionPerformed

    // Event handler untuk klik pada tabel kontak
    private void tblKontakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKontakMouseClicked
        int selectedRow = tblKontak.getSelectedRow(); 
        if (selectedRow != -1 && selectedRow < currentContacts.size()) {
            Kontak selectedContact = currentContacts.get(selectedRow);

            txtNama.setText(selectedContact.getNama());
            txtNama.setForeground(Color.BLACK);

            txtNomorTelepon.setText(selectedContact.getNomorTelepon());
            txtNomorTelepon.setForeground(Color.BLACK);

            cmbKategori.setSelectedItem(selectedContact.getKategori());
        }
        listkontak.clearSelection();
    }//GEN-LAST:event_tblKontakMouseClicked

    // Event handler untuk tombol Hapus
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        deleteContact();
    }//GEN-LAST:event_btnHapusActionPerformed

    // Event handler untuk input keyboard pada field pencarian (real-time search)
    private void txtPencarianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPencarianKeyTyped
        searchContact();
    }//GEN-LAST:event_txtPencarianKeyTyped

    // Event handler untuk tombol Export
    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        exportToCSV();
    }//GEN-LAST:event_btnExportActionPerformed

    // Event handler untuk tombol Import
    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        importFromCSV();
    }//GEN-LAST:event_btnImportActionPerformed

    // Event handler untuk tombol Keluar dengan konfirmasi
    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin keluar dari aplikasi?",
            "Konfirmasi Keluar",
            JOptionPane.YES_NO_OPTION
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    // Event handler untuk tombol Cari Kontak
    private void btnCariKntkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariKntkActionPerformed
        searchContact(); 
    }//GEN-LAST:event_btnCariKntkActionPerformed
    
    // Event handler pengganti ItemListener untuk JComboBox kategori kontak
    private void cmbFilterKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterKategoriActionPerformed
        String selectedFilter = cmbFilterKategori.getSelectedItem().toString().trim();
        if (selectedFilter.equals("Semua")) {
            loadContacts();
        } else {
            filterByKategori(selectedFilter);
        }
    }//GEN-LAST:event_cmbFilterKategoriActionPerformed

    // Event handler untuk tombol Tampilkan Semua (reset filter dan pencarian)
    private void btnTampilkanSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanSemuaActionPerformed
        resetField(txtPencarian);
        cmbFilterKategori.setSelectedIndex(0);
        loadContacts();
        JOptionPane.showMessageDialog(this, "Menampilkan semua kontak.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTampilkanSemuaActionPerformed
    
    // Method untuk memuat semua kontak dari database ke JTable dan JList
    private void loadContacts() { 
        try { 
            model.setRowCount(0); 
            listModel.clear();
            currentContacts = controller.getAllContacts(); 

            int rowNumber = 1; 
            for (Kontak contact : currentContacts) { 
                model.addRow(new Object[]{ 
                    rowNumber++,  
                    contact.getNama(), 
                    contact.getNomorTelepon(), 
                    contact.getKategori() 
                }); 
                listModel.addElement(contact.getNama() + " - " + contact.getNomorTelepon());
            } 
        } catch (SQLException e) { 
            showError(e.getMessage()); 
        }  
    } 

    // Method untuk menampilkan pesan error
    private void showError(String message) { 
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE); 
    }
    
    // Method untuk menambahkan kontak baru ke database
    private void addContact() {       
        String nama = getActualText(txtNama);
        String nomorTelepon = getActualText(txtNomorTelepon);
        String kategori = (String) cmbKategori.getSelectedItem();  
        
        if(nama.isEmpty()){ 
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong.");
            return;
        }

        if (!validatePhoneNumber(nomorTelepon)) { 
            return; 
        } 
        try { 
            if (controller.isDuplicatePhoneNumber(nomorTelepon, null)) { 
                JOptionPane.showMessageDialog(this, "Kontak nomor telepon ini sudah ada.", "Kesalahan", JOptionPane.WARNING_MESSAGE);
                return; 
            }
            
            controller.addContact(nama, nomorTelepon, kategori); 
            loadContacts(); 
            JOptionPane.showMessageDialog(this, "Kontak berhasil ditambahkan!"); 
            clearInputFields(); 
        } catch (SQLException ex) { 
            showError("Gagal menambahkan kontak: " + ex.getMessage()); 
        } 
    }
    
    // Method untuk validasi nomor telepon (hanya angka, panjang 8-15 karakter)
    private boolean validatePhoneNumber(String phoneNumber) { 
        if (phoneNumber == null || phoneNumber.isEmpty()) { 
            JOptionPane.showMessageDialog(this, "Nomor telepon tidak boleh kosong."); 
            return false; 
        } 
        if (!phoneNumber.matches("\\d+")) { // Hanya angka 
            JOptionPane.showMessageDialog(this, "Nomor telepon hanya boleh berisi angka."); 
            return false; 
        } 
        if (phoneNumber.length() < 8 || phoneNumber.length() > 15) { // Panjang 8-15 
            JOptionPane.showMessageDialog(this, "Nomor telepon harus memiliki panjang antara 8 hingga 15 karakter."); 
            return false; 
        } 
        return true; 
    } 

    // Method untuk mengosongkan semua field input
    private void clearInputFields() { 
        resetField(txtNama);
        resetField(txtNomorTelepon);
        cmbKategori.setSelectedIndex(0);  
    }
    
    // Method untuk mengupdate/mengedit kontak yang dipilih
    private void editContact() { 
        int selectedRow = tblKontak.getSelectedRow(); 
        if (selectedRow == -1) { 
            JOptionPane.showMessageDialog(this, "Pilih kontak yang ingin diperbarui.", "Kesalahan", JOptionPane.WARNING_MESSAGE); 
            return; 
        }
        
        // VALIDASI: Pastikan index valid
        if (selectedRow >= currentContacts.size()) {
            JOptionPane.showMessageDialog(this, "Data tidak valid. Silakan refresh.", 
                "Error", JOptionPane.ERROR_MESSAGE);
            loadContacts();
            return;
        }

        int id = currentContacts.get(selectedRow).getId();
        
        String nama = getActualText(txtNama);
        String nomorTelepon = getActualText(txtNomorTelepon);
        String kategori = (String) cmbKategori.getSelectedItem();
        
        if(nama.isEmpty()){ 
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong.");
            return;
        }

        if (!validatePhoneNumber(nomorTelepon)) { 
            return; 
        }
        
        try { 
            if (controller.isDuplicatePhoneNumber(nomorTelepon, id)) { 
                JOptionPane.showMessageDialog(this, "Kontak nomor telepon ini sudah ada.", "Kesalahan", JOptionPane.WARNING_MESSAGE); 
                return; 
            }
             controller.updateContact(id, nama, nomorTelepon, kategori); 
            loadContacts(); 
            JOptionPane.showMessageDialog(this, "Kontak berhasil diperbarui!"); 
            clearInputFields(); 
        } catch (SQLException ex) { 
            showError("Gagal memperbarui kontak: " + ex.getMessage()); 
        } 
    }
    
    // Method untuk menghapus kontak yang dipilih
    private void deleteContact() { 
        int selectedRow = tblKontak.getSelectedRow();
    
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih kontak yang ingin dihapus.", 
                "Kesalahan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (selectedRow >= currentContacts.size()) {
            JOptionPane.showMessageDialog(this, "Data tidak valid. Silakan refresh.", 
                "Error", JOptionPane.ERROR_MESSAGE);
            loadContacts();
            return;
        }

        int id = currentContacts.get(selectedRow).getId();
        String namaKontak = currentContacts.get(selectedRow).getNama();

        int konfirmasi = JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin menghapus kontak:\n" + namaKontak + "?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );

        if (konfirmasi == JOptionPane.YES_OPTION) {
            try { 
                controller.deleteContact(id); 
                loadContacts(); 
                JOptionPane.showMessageDialog(this, "Kontak berhasil dihapus!"); 
                clearInputFields();
            } catch (SQLException e) {
                showError("Gagal menghapus kontak: " + e.getMessage()); 
            } 
        } 
    }
    
    // Method untuk mencari data secara real-time
    private void searchContact() { 
        String keyword = getActualText(txtPencarian); 
        if (!keyword.isEmpty()) { 
            try { 
                currentContacts = controller.searchContacts(keyword); 

                model.setRowCount(0);
                listModel.clear();

                int rowNumber = 1;
                for (Kontak contact : currentContacts) { 
                    model.addRow(new Object[]{ 
                            rowNumber++,
                            contact.getNama(), 
                            contact.getNomorTelepon(), 
                            contact.getKategori() 
                    }); 
                    listModel.addElement(contact.getNama() + " - " + contact.getNomorTelepon());
                } 
                if (currentContacts.isEmpty()) { 
                    JOptionPane.showMessageDialog(this, "Tidak ada kontak ditemukan."); 
                } 
            } catch (SQLException ex) { 
                showError(ex.getMessage()); 
            } 
        } else { 
            loadContacts(); 
        } 
    } 
    
    // Method untuk menyimpan atau mendownload data CSV yang sudah dibuat
    private void exportToCSV() { 
        JFileChooser fileChooser = new JFileChooser(); 
        fileChooser.setDialogTitle("Simpan File CSV"); 
        int userSelection = fileChooser.showSaveDialog(this); 
        if (userSelection == JFileChooser.APPROVE_OPTION) { 
            File fileToSave = fileChooser.getSelectedFile(); 

            // Tambahkan ekstensi .csv jika pengguna tidak menambahkannya 
            if (!fileToSave.getAbsolutePath().endsWith(".csv")) { 
                fileToSave = new File(fileToSave.getAbsolutePath() + ".csv"); 
            }
            
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileToSave))) {
                writer.write("ID,Nama,Nomor Telepon,Kategori\n");
                // Header CSV
                for (int i = 0; i < model.getRowCount(); i++) { 
                    writer.write( 
                        model.getValueAt(i, 0) + "," + 
                        model.getValueAt(i, 1) + "," + 
                        model.getValueAt(i, 2) + "," + 
                        model.getValueAt(i, 3) + "\n" 
                    ); 
                }
                JOptionPane.showMessageDialog(this, "Data berhasil diekspor ke " + fileToSave.getAbsolutePath());
            } catch (IOException ex) { 
                showError("Gagal menulis file: " + ex.getMessage()); 
            } 
        } 
    }   
    
    // Method untuk Memasukkan Data CSV ke aplikasi 
    private void importFromCSV() { 
        showCSVGuide(); 

        int confirm = JOptionPane.showConfirmDialog( 
            this, 
            "Apakah Anda yakin file CSV yang dipilih sudah sesuai dengan format?", 
            "Konfirmasi Impor CSV", 
            JOptionPane.YES_NO_OPTION 
        );
        
        if (confirm == JOptionPane.YES_OPTION) { 
            JFileChooser fileChooser = new JFileChooser(); 
            fileChooser.setDialogTitle("Pilih File CSV");
            
            int userSelection = fileChooser.showOpenDialog(this);
            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File fileToOpen = fileChooser.getSelectedFile(); 
                
                try (BufferedReader reader = new BufferedReader(new FileReader(fileToOpen))) {
                    String line = reader.readLine(); // Baca header
                    
                    if (!validateCSVHeader(line)) {
                        JOptionPane.showMessageDialog(
                            this,
                            "Format header CSV tidak valid.\nPastikan header: ID,Nama,Nomor Telepon,Kategori",
                            "Kesalahan CSV",
                            JOptionPane.ERROR_MESSAGE
                        );
                        return;
                    }
                    
                    int rowCount = 0;
                    int errorCount = 0;
                    int duplicateCount = 0;
                    
                    StringBuilder errorLog = new StringBuilder("Baris dengan kesalahan:\n");
                    
                    while ((line = reader.readLine()) != null) {
                        rowCount++;
                        String[] data = line.split(",");

                        if (data.length != 4) {
                            errorCount++;
                            errorLog.append("Baris ").append(rowCount + 1).append(": Format kolom tidak sesuai.\n");
                            continue;
                        }
                        
                        String nama = data[1].trim();
                        String nomorTelepon = data[2].trim();
                        String kategori = data[3].trim();
                        
                        if (nama.isEmpty() || nomorTelepon.isEmpty()) {
                            errorCount++;
                            errorLog.append("Baris ").append(rowCount + 1).append(": Nama atau Nomor Telepon kosong.\n");
                            continue;
                        }
                        
                        if (!validatePhoneNumber(nomorTelepon)) {
                            errorCount++;
                            errorLog.append("Baris ").append(rowCount + 1).append(": Nomor Telepon tidak valid.\n");
                            continue;
                        }
                        
                        if (!isValidKategori(kategori)) {
                            errorCount++;
                            errorLog.append("Baris ").append(rowCount + 1)
                                    .append(": Kategori tidak valid. Harus Keluarga, Teman, atau Kantor.\n");
                            continue;
                        }
                        
                        try {
                            if (controller.isDuplicatePhoneNumber(nomorTelepon, null)) {
                                duplicateCount++;
                                errorLog.append("Baris ").append(rowCount + 1).append(": Kontak sudah ada.\n");
                                continue;
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(PengelolaanKontakFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
                        try {
                            controller.addContact(nama, nomorTelepon, kategori);
                        } catch (SQLException ex) {
                            errorCount++;
                            errorLog.append("Baris ").append(rowCount + 1)
                                    .append(": Gagal menyimpan ke database - ").append(ex.getMessage()).append("\n");
                        }
                    }
                    
                    loadContacts();
                    
                    if (errorCount > 0 || duplicateCount > 0) {
                        errorLog.append("\nTotal baris kesalahan: ").append(errorCount).append("\n")
                                .append("Total baris duplikat: ").append(duplicateCount).append("\n");

                        JOptionPane.showMessageDialog(this, errorLog.toString(), "Kesalahan Impor",
                                JOptionPane.WARNING_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Semua data berhasil diimpor.");
                    }

                } catch (IOException ex) {
                    showError("Gagal membaca file: " + ex.getMessage());
                }
            }
        }
    }
    
    // Method validasi kategori
    private boolean isValidKategori(String kategori) {
        return kategori.equals("Keluarga") || 
               kategori.equals("Teman") || 
               kategori.equals("Kantor");
    }
    
    // Method menampilkan filter kategori pada JComboBox
    private void filterByKategori(String kategori) {
        try {
            model.setRowCount(0);
            listModel.clear();

            List<Kontak> allContacts = controller.getAllContacts();
            currentContacts = new ArrayList<>(); 

            int rowNumber = 1; 
            for (Kontak c : allContacts) {
                if (kategori.trim().equals(c.getKategori().trim())) {
                    currentContacts.add(c); 
                    model.addRow(new Object[]{
                        rowNumber++,
                        c.getNama(), 
                        c.getNomorTelepon(), 
                        c.getKategori()
                    });
                    listModel.addElement(c.getNama() + " - " + c.getNomorTelepon());
                }
            }

            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Tidak ada kontak di kategori ini.");
            }

        } catch (SQLException e) {
            showError(e.getMessage());
        }
    }
    
    private void showCSVGuide() {
        String guideMessage =
            "Format CSV untuk impor data:\n" +
            "- Header wajib: ID,Nama,Nomor Telepon,Kategori\n" +
            "- ID boleh kosong (otomatis)\n" +
            "- Nama & Nomor Telepon wajib diisi\n\n" +
            "Contoh:\n" +
            "1, Andi, 08123456789, Teman\n" +
            "2, Budi Doremi, 08567890123, Keluarga\n\n" +
            "Pastikan file CSV sesuai format sebelum melakukan impor.";

        JOptionPane.showMessageDialog(this, guideMessage, "Panduan Format CSV",
                JOptionPane.INFORMATION_MESSAGE);
    }
    
    private boolean validateCSVHeader(String header) {
        if (header == null) return false;
        
        String cleanedHeader = header.replaceAll("\\s+", "");
        String expectedHeader = "ID,Nama,NomorTelepon,Kategori";
        
        return cleanedHeader.equalsIgnoreCase(expectedHeader);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PengelolaanKontakFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PengelolaanKontakFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PengelolaanKontakFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PengelolaanKontakFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PengelolaanKontakFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariKntk;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTampilkanSemua;
    private javax.swing.JComboBox<String> cmbFilterKategori;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDaftarKntk;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblKontak;
    private javax.swing.JLabel lblPencarian;
    private javax.swing.JLabel lblTelepon;
    private javax.swing.JList<String> listkontak;
    private javax.swing.JTable tblKontak;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNomorTelepon;
    private javax.swing.JTextField txtPencarian;
    // End of variables declaration//GEN-END:variables
}
